server:
  port: 8082

spring:
  application:
    name: jackpot-service

  webflux:
    base-path: /jackpot-service   # Correct for WebFlux

  r2dbc:
    url: r2dbc:h2:mem:///jackpotdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      continue-on-error: true

  h2:
    console:
      enabled: true
      path: /h2-console   # Access via http://localhost:8082/jackpot-service/h2-console

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: jackpot-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.jackpot.model
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        linger.ms: 5
        batch.size: 16384
        compression.type: snappy

management:
  endpoints:
    web:
      base-path: /jackpot-service/actuator
      exposure:
        include: "*"

jackpot:
  fixed:
    percentage: 0.20
    threshold: 5000
  variable:
    divisor: 7
    threshold: 5000
    lowFactor: 0.05
    highFactor: 0.10

logging:
  level:
    root: INFO
    org.springframework.kafka: INFO
    org.springframework.web.reactive.result.method.annotation.RequestMappingHandlerMapping: TRACE
